# Generated by Django 5.0.4 on 2026-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("priceapp", "0002_dealer_created_at_dealer_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vp_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
