# Generated by Django 5.0.4 on 2026-04-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("priceapp", "0003_product_vp_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="price_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productprice",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
