# Generated by Django 5.0.4 on 2026-10-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0005_product_barcode_product_barcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
